{"name": "Проверка ошибки принятия заказа из-за несуществующего id курьера", "status": "passed", "start": 1720188154930, "stop": 1720188155113, "uuid": "aa0e28d4-b367-46d4-9158-77ff24fac4dc", "historyId": "f984fb2dfea3096d9183830a02c98e61", "testCaseId": "f984fb2dfea3096d9183830a02c98e61", "fullName": "tests.test_accept_order.test_accept_order_fail.TestAcceptOrderFail#test_accept_order_wrong_courier_id", "labels": [{"name": "parentSuite", "value": "tests.test_accept_order"}, {"name": "suite", "value": "test_accept_order_fail"}, {"name": "subSuite", "value": "TestAcceptOrderFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "11792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order.test_accept_order_fail"}]}