{"name": "Проверка ошибки принятия заказа из-за несуществующего id курьера", "status": "passed", "start": 1720032090578, "stop": 1720032090783, "uuid": "cada3be9-4315-4566-8767-9fa07c784e01", "historyId": "f984fb2dfea3096d9183830a02c98e61", "testCaseId": "f984fb2dfea3096d9183830a02c98e61", "fullName": "tests.test_accept_order.test_accept_order_fail.TestAcceptOrderFail#test_accept_order_wrong_courier_id", "labels": [{"name": "parentSuite", "value": "tests.test_accept_order"}, {"name": "suite", "value": "test_accept_order_fail"}, {"name": "subSuite", "value": "TestAcceptOrderFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "1872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order.test_accept_order_fail"}]}