{"name": "Проверка ошибки получения заказа из-за неправильного номера", "status": "passed", "start": 1720032093901, "stop": 1720032094117, "uuid": "0810ff30-caa4-4a65-9838-92e1c67ccddd", "historyId": "bdaeacc1a27af1d70a454721bf8c9618", "testCaseId": "bdaeacc1a27af1d70a454721bf8c9618", "fullName": "tests.test_get_order_by_track.test_get_order_by_track_fail.TestAcceptOrderByTrackFail#test_get_order_by_track_success", "labels": [{"name": "parentSuite", "value": "tests.test_get_order_by_track"}, {"name": "suite", "value": "test_get_order_by_track_fail"}, {"name": "subSuite", "value": "TestAcceptOrderByTrackFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "1872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_track.test_get_order_by_track_fail"}]}