{"name": "Проверка ошибки получения заказа из-за неправильного номера", "status": "passed", "start": 1720188158834, "stop": 1720188159061, "uuid": "f54cd02c-ed31-4f88-9635-5d5efe92f153", "historyId": "bdaeacc1a27af1d70a454721bf8c9618", "testCaseId": "bdaeacc1a27af1d70a454721bf8c9618", "fullName": "tests.test_get_order_by_track.test_get_order_by_track_fail.TestAcceptOrderByTrackFail#test_get_order_by_track_success", "labels": [{"name": "parentSuite", "value": "tests.test_get_order_by_track"}, {"name": "suite", "value": "test_get_order_by_track_fail"}, {"name": "subSuite", "value": "TestAcceptOrderByTrackFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "11792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_track.test_get_order_by_track_fail"}]}