{"name": "Проверка ошибки принятия заказа из-за несуществующего id заказа", "status": "passed", "start": 1720188156028, "stop": 1720188156205, "uuid": "722cd829-7f5a-4090-9a36-0867855d1a50", "historyId": "3a6edd468f4d627d85bdca745ff6982d", "testCaseId": "3a6edd468f4d627d85bdca745ff6982d", "fullName": "tests.test_accept_order.test_accept_order_fail.TestAcceptOrderFail#test_accept_order_wrong_order_id", "labels": [{"name": "parentSuite", "value": "tests.test_accept_order"}, {"name": "suite", "value": "test_accept_order_fail"}, {"name": "subSuite", "value": "TestAcceptOrderFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "11792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order.test_accept_order_fail"}]}