{"name": "Проверка ошибки принятия заказа из-за несуществующего id заказа", "status": "passed", "start": 1720032091595, "stop": 1720032091816, "uuid": "166e22b8-9fd9-4ac4-bdde-086cca27e11d", "historyId": "3a6edd468f4d627d85bdca745ff6982d", "testCaseId": "3a6edd468f4d627d85bdca745ff6982d", "fullName": "tests.test_accept_order.test_accept_order_fail.TestAcceptOrderFail#test_accept_order_wrong_order_id", "labels": [{"name": "parentSuite", "value": "tests.test_accept_order"}, {"name": "suite", "value": "test_accept_order_fail"}, {"name": "subSuite", "value": "TestAcceptOrderFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "1872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order.test_accept_order_fail"}]}